server:
  port: 8080

spring:
  datasource:
    clickhouse:
      address: jdbc:clickhouse://212.64.90.199:8123
      username: root
      password: 123456
      db: system
      socketTimeout: 600000

clickhouse:
  url: jdbc:clickhouse://212.64.90.199:8123
  username: root
  password: 123456
  db: test1
  socketTimeout: 600000