server:
  port: 8082

spring:
  application:
    name: ruizhi-platform
    version: 1.0.0.1
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
