server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/static/html/
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/ddl.sql
    data: classpath:db/dml.sql
    url: jdbc:h2:~/isa
    username: dbuser
    password: dbuser
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.alkaid.isa.config.pojo