server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itone
    username: dbuser
    password:
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/static/html/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.its.itone.sas.config
  type-handlers-package: com.its.itone.sas.config.mybatis.typehandler
druid:
  maxActive: 50
  initialSize: 10
  maxWait: 60000
  minIdle: 6
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20